<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- Project Information -->
    <groupId>com.example</groupId>
    <artifactId>iceberg-example</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <iceberg.version>1.4.0</iceberg.version> <!-- Use the latest version -->
    </properties>

    <dependencies>
        <!-- Apache Iceberg Core Dependency -->
    <dependencies>
        <dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-core</artifactId>
            <!-- Latest Core Version -->
            <version>1.8.0</version>
        </dependency>
    </dependencies>


        <!-- Add other Iceberg modules if needed -->
        <dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-common</artifactId>
            <!-- Check the version -->
            <!--  -->
            <version>${iceberg.version}</version>
        </dependency>

        <!-- Add Spark runtime if you're using Iceberg with Spark -->
        <dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-spark-runtime</artifactId>
            <!-- check the version -->
            <!--  -->
            <version>${iceberg.version}</version>
        </dependency>

        <!-- Add other dependencies as needed -->
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-client</artifactId>
            <version>3.3.6</version> <!-- Use the version compatible with your setup -->
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Maven Compiler Plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
